from typing import Dict, List, Any

class GitHubPatchPublisher:
    def __init__(self):
        pass

    def format_suggested_changes_comment(
        self, patch_items: List[Dict[str, Any]], validation_result: Dict[str, Any]
    ) -> str:
        """
        Formats validated patches into GitHub PR Suggested Changes Markdown blocks.
        """
        val_success = validation_result.get("success", False)
        status_str = "**PASSED (All Tests Verified)**" if val_success else "**NEEDS REVIEW (Validation Failed)**"

        lines = [
            "## MergeLens Automated Migration Patch",
            f"Validation Status: {status_str}",
            "",
            "The following automated code changes were generated to adapt to the dependency upgrade:",
            ""
        ]

        for item in patch_items:
            f_path = item.get("file_path", "")
            orig = item.get("original_snippet", "")
            repl = item.get("replacement_snippet", "")

            lines.append(f"### File: `{f_path}`")
            lines.append("```diff")
            lines.append(f"- {orig}")
            lines.append(f"+ {repl}")
            lines.append("```")
            lines.append("")

        if not val_success:
            err_log = validation_result.get("logs", "Validation failed.")
            lines.append("### Validation Failure Logs:")
            lines.append(f"```\n{err_log[:1500]}\n```\n")

        lines.append("---")
        lines.append("*Automated patch generated by MergeLens AI Patch Synthesizer*")

        return "\n".join(lines)
