from typing import Dict, Any

class ReportFormatter:
    def __init__(self):
        pass

    def format_pr_comment(
        self,
        repository_name: str,
        pr_number: int,
        dependency_name: str,
        from_version: str,
        to_version: str,
        ai_synthesis: Dict[str, Any],
        impact_summary: Dict[str, Any]
    ) -> str:
        """
        Formats analysis findings into a professional GitHub Pull Request Comment in Markdown format.
        """
        priority = ai_synthesis.get("priority_score", 0)
        risk = ai_synthesis.get("risk_score", "low").upper()
        confidence = ai_synthesis.get("confidence_score", 0)
        recommendation = ai_synthesis.get("recommendation", "Review before merging.")
        exec_summary = ai_synthesis.get("executive_summary", "")

        lines = [
            f"## MergeLens Dependency Impact Review",
            f"### `{dependency_name}` upgrade `{from_version}` &rarr; `{to_version}`",
            "",
            f"| Priority Score | Risk Level | Confidence |",
            f"| :---: | :---: | :---: |",
            f"| **{priority} / 100** | **{risk}** | **{confidence}%** |",
            "",
            f"### Executive Summary",
            f"{exec_summary}",
            "",
            f"**Recommendation:** {recommendation}",
            "",
            "---",
            "### Codebase Impact Breakdown",
        ]

        # Direct Impacts
        direct_impacts = impact_summary.get("direct_impacts", [])
        if direct_impacts:
            lines.append("#### Direct Breaking API Usages:")
            for imp in direct_impacts:
                lines.append(
                    f"* File `{imp.get('file_path')}` (L{imp.get('line_number')}): "
                    f"Uses `{imp.get('imported_symbol')}` (`{imp.get('change_type')}`)"
                )
            lines.append("")
        else:
            lines.append("* **Direct Breaking API Calls:** None detected in codebase.\n")

        # Import Warnings
        import_warnings = impact_summary.get("import_warnings", [])
        if import_warnings:
            lines.append("#### Import Warnings:")
            for w in import_warnings:
                lines.append(f"* `{w.get('file_path')}`: {w.get('warning')}")
            lines.append("")

        # Affected Files & Call Chains
        affected_files = impact_summary.get("affected_files", [])
        if affected_files:
            lines.append("#### Affected Files:")
            for f_path in affected_files:
                lines.append(f"* `{f_path}`")
            lines.append("")

        call_chains = impact_summary.get("call_chains", [])
        if call_chains:
            lines.append("#### Impacted Call Chains:")
            for chain in call_chains:
                lines.append(f"* `{' -> '.join(chain)}`")
            lines.append("")

        # Migration Steps
        migration_steps = ai_synthesis.get("migration_steps", [])
        if migration_steps:
            lines.append("### Recommended Migration Steps")
            for idx, step in enumerate(migration_steps, start=1):
                lines.append(f"{idx}. {step}")
            lines.append("")

        # Suggested Tests
        suggested_tests = impact_summary.get("suggested_tests", [])
        if suggested_tests:
            lines.append("### Suggested Test Suites to Run")
            for t_file in suggested_tests:
                lines.append(f"* `{t_file}`")
            lines.append("")

        # Security Notes
        sec_notes = ai_synthesis.get("security_notes", "")
        if sec_notes:
            lines.append(f"### Security Notes\n{sec_notes}\n")

        lines.append("---")
        lines.append("*Automated report generated by MergeLens AI*")

        return "\n".join(lines)
