"""Add release_facts table

Revision ID: 2e97f36fe455
Revises: bc555f48f98d
Create Date: 2026-07-22 23:09:39.107813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e97f36fe455'
down_revision: Union[str, Sequence[str], None] = 'bc555f48f98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('from_version', sa.String(), nullable=False),
    sa.Column('to_version', sa.String(), nullable=False),
    sa.Column('release_notes_raw', sa.String(), nullable=True),
    sa.Column('breaking_apis_json', sa.JSON(), nullable=True),
    sa.Column('behavior_changes_json', sa.JSON(), nullable=True),
    sa.Column('security_fixes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_facts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_facts_package_name'), ['package_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_facts_package_name'))
        batch_op.drop_index(batch_op.f('ix_release_facts_id'))

    op.drop_table('release_facts')
    # ### end Alembic commands ###
