"""Initial schema setup

Revision ID: 4864023fa867
Revises: 
Create Date: 2026-07-18 02:37:30.632255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4864023fa867'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('git_url', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('indexing_status', sa.String(), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_name'), ['name'], unique=True)

    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('dependency_name', sa.String(), nullable=False),
    sa.Column('from_version', sa.String(), nullable=False),
    sa.Column('to_version', sa.String(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_reports_id'), ['id'], unique=False)

    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_name'))
        batch_op.drop_index(batch_op.f('ix_dependencies_id'))

    op.drop_table('dependencies')
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_reports_id'))

    op.drop_table('analysis_reports')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_name'))
        batch_op.drop_index(batch_op.f('ix_repositories_id'))

    op.drop_table('repositories')
    # ### end Alembic commands ###
