"""Add symbol and api_usage tables

Revision ID: bc555f48f98d
Revises: 4864023fa867
Create Date: 2026-07-18 02:49:29.041226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc555f48f98d'
down_revision: Union[str, Sequence[str], None] = '4864023fa867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('imported_symbol', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usages_imported_symbol'), ['imported_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usages_package_name'), ['package_name'], unique=False)

    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symbols_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbols_name'), ['name'], unique=False)

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dependency_graph_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('call_graph_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_column('call_graph_json')
        batch_op.drop_column('dependency_graph_json')

    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbols_name'))
        batch_op.drop_index(batch_op.f('ix_symbols_id'))

    op.drop_table('symbols')
    with op.batch_alter_table('api_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usages_package_name'))
        batch_op.drop_index(batch_op.f('ix_api_usages_imported_symbol'))
        batch_op.drop_index(batch_op.f('ix_api_usages_id'))

    op.drop_table('api_usages')
    # ### end Alembic commands ###
